//create table view data object
function getlist(){
    return [
        {title:'初心者のためのPerlの入門 (perlintro)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlintro.pod'},
        {title:'Perlリファレンスの短い入門 (perlreftut)', url_ja:'http://perldoc.jp/docs/perl/5.10.0/perlreftut.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlreftut.pod'},
        {title:'Perlデータ構造入門 (perldsc)', url_ja:'http://perldoc.jp/docs/perl/5.10.0/perldsc.pod', url_en:'http://search.cpan.org/dist/perl/pod/perldsc.pod'},
        {title:'Perlデータ構造: 配列の配列 (perllol)', url_ja:'http://perldoc.jp/docs/perl/5.6.1/perllol.pod', url_en:'http://search.cpan.org/dist/perl/pod/perllol.pod'},
        {title:'Perl正規表現クイックスタート (perlrequick)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlrequick.pod'},
        {title:'Perl正規表現入門 (perlretut)', url_ja:'http://perldoc.jp/docs/perl/5.10.0/perlretut.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlretut.pod'},
        {title:'初心者のためのPerlオブジェクト指向入門 (perlboot)', url_ja:'http://fleur.hio.jp/perldoc/mix/pod/perlboot.html', url_en:'http://search.cpan.org/dist/perl/pod/perlboot.pod'},
        {title:'Perlオブジェクト指向入門 その1 (perltoot)', url_ja:'http://perldoc.jp/docs/perl/5.10.0/perltoot.pod', url_en:'http://search.cpan.org/dist/perl/pod/perltoot.pod'},
        {title:'Perlオブジェクト指向入門 その2 (perltooc)', url_ja:'http://perldoc.jp/docs/perl/5.10.0/perltooc.pod', url_en:'http://search.cpan.org/dist/perl/pod/perltooc.pod'},
        {title:'Perlオブジェクト指向 秘訣とサンプル (perlbot)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlbot.pod'},
        {title:'Perlパフォーマンスと最適化のテクニック (perlperf)', url_ja:'http://d.hatena.ne.jp/keyword/%BA%C7%C5%AC%B2%BD', url_en:'http://search.cpan.org/dist/perl/pod/perlperf.pod'},
        {title:'Perlスタイルガイド (perlstyle)', url_ja:'http://perldoc.jp/docs/perl/5.8.0/perlstyle.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlstyle.pod'},
        {title:'Perlチートシート (perlcheat)', url_ja:'http://fleur.hio.jp/perldoc/mix/pod/perlcheat.mix.html', url_en:'http://search.cpan.org/dist/perl/pod/perlcheat.pod'},
        {title:'Perlの不注意による罠 (perltrap)', url_ja:'http://perldoc.jp/docs/perl/5.6.1/perltrap.pod', url_en:'http://search.cpan.org/dist/perl/pod/perltrap.pod'},
        {title:'Perlデバッグ入門 (perldebtut)', url_ja:'http://perldoc.jp/docs/perl/5.10.0/perldebtut.pod', url_en:'http://search.cpan.org/dist/perl/pod/perldebtut.pod'},
        {title:'しばしば尋ねられるPerlの質問 (perlfaq) Perlに関する一般的な質問 (perlfaq1)Perlの入手と学習 (perlfaq2)プログラミングツール (perlfaq3)データ操作 (perlfaq4)ファイルとフォーマット (perlfaq5)正規表現 (perlfaq6)Perl言語の問題 (perlfaq7)システムとの相互作用 (perlfaq8)ネットワーク (perlfaq9)', url_ja:'http://perldoc.jp/docs/perl/5.10.0/perlfaq.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlfaq.pod'},
        {title:'Perlの文法 (perlsyn)', url_ja:'http://perldoc.jp/docs/perl/5.8.8/perlsyn.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlsyn.pod'},
        {title:'Perlのデータ構造 (perldata)', url_ja:'http://perldoc.jp/docs/perl/5.8.8/perldata.pod', url_en:'http://search.cpan.org/dist/perl/pod/perldata.pod'},
        {title:'Perl演算子と優先順位 (perlop)', url_ja:'http://perldoc.jp/docs/perl/5.8.8/perlop.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlop.pod'},
        {title:'Perlサブルーチン (perlsub)', url_ja:'http://perldoc.jp/docs/perl/5.10.0/perlsub.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlsub.pod'},
        {title:'Perl組み込み関数 (perlfunc) Perl open() 入門 (perlopentut)Perl pack()とunpack()の入門 (perlpacktut)', url_ja:'http://perldoc.jp/docs/perl/5.6.1/perlfunc.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlfunc.pod'},
        {title:'Perlプレインオールドドキュメンテーション (perlpod)', url_ja:'http://perldoc.jp/docs/perl/5.8.4/perlpod.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlpod.pod'},
        {title:'Perlプレインオールドドキュメンテーションのフォーマット仕様 (perlpodspec)', url_ja:'http://d.hatena.ne.jp/keyword/%A5%C9%A5%AD%A5%E5%A5%E1%A5%F3%A5%C6%A1%BC%A5%B7%A5%E7%A5%F3', url_en:'http://search.cpan.org/dist/perl/pod/perlpodspec.pod'},
        {title:'Perの実行とオプション (perlrun)', url_ja:'http://perldoc.jp/docs/perl/5.6.1/perlrun.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlrun.pod'},
        {title:'Perlの診断メッセージ (perldiag)', url_ja:'http://perldoc.jp/docs/perl/5.6.1/perldiag.pod', url_en:'http://search.cpan.org/dist/perl/pod/perldiag.pod'},
        {title:'Perlの警告とそのコントロール (perllexwarn)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perllexwarn.pod'},
        {title:'Perlデバッグ (perldebug)', url_ja:'http://perldoc.jp/docs/perl/5.8.8/perldebug.pod', url_en:'http://search.cpan.org/dist/perl/pod/perldebug.pod'},
        {title:'Perlの定義済み変数 (perlvar)', url_ja:'http://perldoc.jp/docs/perl/5.6.1/perlvar.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlvar.pod'},
        {title:'Perl正規表現 話の残り (perlre)', url_ja:'http://fleur.hio.jp/perldoc/perl/5.9.5/pod/perlre.mix.html', url_en:'http://search.cpan.org/dist/perl/pod/perlre.pod'},
        {title:'Perl正規表現 バックスラッシュシーケンス (perlrebackslash)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlrebackslash.pod'},
        {title:'Perl正規表現 文字クラス (perlrecharclass)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlrecharclass.pod'},
        {title:'Perl正規表現 クイックリファレンス (perlreref)', url_ja:'http://perldoc.jp/docs/perl/5.10.0/perlreref.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlreref.pod'},
        {title:'Perlリファレンス 残りの話 (perlref)', url_ja:'http://perldoc.jp/docs/perl/5.8.8/perlref.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlref.pod'},
        {title:'Perlフォーマット (perlform)', url_ja:'http://perldoc.jp/docs/perl/5.8.8/perlform.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlform.pod'},
        {title:'Perlオブジェクト (perlobj)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlobj.pod'},
        {title:'単純な変数の後ろに隠れたPerlオブジェクト (perltie) Perl DBM フィルター (perldbmfilter)', url_ja:'http://perldoc.jp/docs/perl/5.8.8/perltie.pod', url_en:'http://search.cpan.org/dist/perl/pod/perltie.pod'},
        {title:'Perlプロセス間通信 (perlipc)', url_ja:'http://perldoc.jp/docs/perl/5.8.8/perlipc.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlipc.pod'},
        {title:'Perl fork() 情報 (perlfork)', url_ja:'http://fleur.hio.jp/perldoc/mix/pod/perlfork.html', url_en:'http://search.cpan.org/dist/perl/pod/perlfork.pod'},
        {title:'Perl数値の動作 (perlnumber)', url_ja:'http://perldoc.jp/docs/perl/5.10.0/perlnumber.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlnumber.pod'},
        {title:'Perlスレッド入門 (perlthrtut)', url_ja:'http://perldoc.jp/docs/perl/5.10.0/perlthrtut.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlthrtut.pod'},
        {title:'Perl ポータビリティガイド(perlport)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlport.pod'},
        {title:'Perlロケールサポート (perllocale)', url_ja:'http://perldoc.jp/docs/perl/5.8.8/perllocale.pod', url_en:'http://search.cpan.org/dist/perl/pod/perllocale.pod'},
        {title:'Perl Unicode入門(introduction) (perluniintro)', url_ja:'http://perldoc.jp/docs/perl/5.10.0/perluniintro.pod', url_en:'http://search.cpan.org/dist/perl/pod/perluniintro.pod'},
        {title:'Perl Unicodeサポート (perlunicode)', url_ja:'http://perldoc.jp/docs/perl/5.10.0/perlunicode.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlunicode.pod'},
        {title:'Perl Unicode FAQ (perlunifaq)', url_ja:'http://perldoc.jp/docs/perl/5.10.0/perlunifaq.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlunifaq.pod'},
        {title:'PerlにおけるUnicodeバージョン5.2.0プロパティの一覧 (perluniprops)', url_ja:'', url_en:'http://perldoc.perl.org/perluniprops.html'},
        {title:'Perl Unicode入門(tutorial) (perlunitut)', url_ja:'http://perldoc.jp/docs/perl/5.10.0/perlunitut.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlunitut.pod'},
        {title:'EBCDICプラットフォーム上でPerlを実行するための考慮 (perlebcdic)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlebcdic.pod'},
        {title:'Perlセキュリティ (perlsec)', url_ja:'http://perldoc.jp/docs/perl/5.6.1/perlsec.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlsec.pod'},
        {title:'Perl モジュール: どのように動くか (perlmod)', url_ja:'http://perldoc.jp/docs/perl/5.8.8/perlmod.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlmod.pod'},
        {title:'Perl モジュール: どのように書いて使うか (perlmodlib)', url_ja:'http://d.hatena.ne.jp/keyword/%A5%E2%A5%B8%A5%E5%A1%BC%A5%EB', url_en:'http://search.cpan.org/dist/perl/pod/perlmodlib.pod'},
        {title:'Perl モジュール: どのようにモジュールをうまく書くか (perlmodstyle)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlmodstyle.pod'},
        {title:'Perl モジュール: CPANからインストールする方法 (perlmodinstall)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlmodinstall.pod'},
        {title:'Perl モジュール: 配布のための新しいモジュールの準備 (perlnewmod)', url_ja:'http://perldoc.jp/docs/perl/5.8.0/perlnewmod.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlnewmod.pod'},
        {title:'Perl モジュール: ユーザプラグマを書く (perlpragma)', url_ja:'http://fleur.hio.jp/perldoc/mix/pod/perlpragma.html', url_en:'http://search.cpan.org/dist/perl/pod/perlpragma.pod'},
        {title:'Perlディストリビューションに含まれているユーティリティ (perlutil)', url_ja:'http://d.hatena.ne.jp/keyword/%A5%C7%A5%A3%A5%B9%A5%C8%A5%EA%A5%D3%A5%E5%A1%BC%A5%B7%A5%E7%A5%F3', url_en:'http://search.cpan.org/dist/perl/pod/perlutil.pod'},
        {title:'Perlコンパイラのひとそろいの入門 (perlcompile)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlcompile.pod'},
        {title:'Perlソースフィルタ (perlfilter)', url_ja:'', url_en:'http://perldoc.perl.org/perlfilter.html'},
        {title:'Perl用語集 (perlglossary)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlglossary.pod'},
        {title:'CあるいはC++アプリケーションにPerlに埋め込む方法 (perlembed)', url_ja:'http://perldoc.jp/docs/perl/5.10.0/perlembed.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlembed.pod'},
        {title:'Perlの中身のデバッグとヒント] (perldebguts)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perldebguts.pod'},
        {title:'Perl XS入門 (perlxstut)', url_ja:'http://perldoc.jp/docs/perl/5.8.8/perlxstut.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlxstut.pod'},
        {title:'Perl XSアプリケーションプラグラミングインターフェース (perlxs)', url_ja:'http://perldoc.jp/docs/perl/5.8.8/perlxs.pod', url_en:'http://search.cpan.org/dist/perl/pod/perlxs.pod'},
        {title:'標準Cライブラリ関数の内部的な代用 (perlclib)', url_ja:'http://d.hatena.ne.jp/keyword/%B4%D8%BF%F4', url_en:'http://search.cpan.org/dist/perl/pod/perlclib.pod'},
        {title:'エクステンションを書く人のためのPerlの内部関数 (perlguts)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlguts.pod'},
        {title:'CからのPerlの呼び出し規約 (perlcall)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlcall.pod'},
        {title:'Perlメソッド解決プラグインインターフェース (perlmroapi)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlmroapi.pod'},
        {title:'Perl正規表現プラグインインターフェース (perlreapi)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlreapi.pod'},
        {title:'Perl正規表現エンジンの内部 (perlreguts)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlreguts.pod'},
        {title:'Perl API リスト (perlapi)', url_ja:'', url_en:'http://perldoc.perl.org/perlapi.html'},
        {title:'Perl内部関数 (perlintern)', url_ja:'', url_en:'http://perldoc.perl.org/perlintern.html'},
        {title:'レイヤー化されたPerlIO実装のためのC API (perliol)', url_ja:'http://d.hatena.ne.jp/keyword/%A5%EC%A5%A4%A5%E4%A1%BC', url_en:'http://search.cpan.org/dist/perl/pod/perliol.pod'},
        {title:'Perl 内部IO抽象インターフェース (perlapio)', url_ja:'http://argrath.ub32.org/perldocjp/5.10.0/perlapio.html', url_en:'http://search.cpan.org/dist/perl/pod/perlapio.pod'},
        {title:'Perlハッカーガイド (perlhack)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlhack.pod'},
        {title:'Perl開発ポリシー (perlpolicy)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlpolicy.pod'},
        {title:'Perlソースリポジトリ(perlrepository)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlrepository.pod'},
        {title:'Perl書籍情報 (perlbook)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlbook.pod'},
        {title:'Perlコミュニティ情報 (perlcommunity)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlcommunity.pod'},
        {title:'Perl 行う必要のあること (perltodo)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perltodo.pod'},
        {title:'PodフォーマットでPerlドキュメンテーションを調べる (perldoc)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perldoc.pod'},
        {title:'Perlの歴史の記録 (perlhist)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perlhist.pod'},
        {title:'前バージョンからのPerlの変更 (perldelta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perldelta.pod'},
        {title:'Perlバージョン5.12.0における変更点 (perl5120delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl5120delta.pod'},
        {title:'Perlバージョン5.11.5における変更点 (perl5115delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl5115delta.pod'},
        {title:'Perlバージョン5.11.4における変更点 (perl5114delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl5114delta.pod'},
        {title:'Perlバージョン5.11.3における変更点 (perl5113delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl5113delta.pod'},
        {title:'Perlバージョン5.11.2における変更点 (perl5112delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl5112delta.pod'},
        {title:'Perlバージョン5.11.1における変更点 (perl5111delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl5111delta.pod'},
        {title:'Perlバージョン5.11.0における変更点 (perl5110delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl5110delta.pod'},
        {title:'Perlバージョン5.10.1における変更点 (perl5101delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl5101delta.pod'},
        {title:'Perlバージョン5.10.0における変更点 (perl5100delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl5100delta.pod'},
        {title:'Perlバージョン5.9.5における変更点 (perl595delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl595delta.pod'},
        {title:'Perlバージョン5.9.4における変更点 (perl594delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl594delta.pod'},
        {title:'Perlバージョン5.9.3における変更点 (perl593delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl593delta.pod'},
        {title:'Perlバージョン5.9.2における変更点 (perl592delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl592delta.pod'},
        {title:'Perlバージョン5.9.1における変更点 (perl591delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl591delta.pod'},
        {title:'Perlバージョン5.9.0における変更点 (perl590delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl590delta.pod'},
        {title:'Perlバージョン5.8.9における変更点 (perl589delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl589delta.pod'},
        {title:'Perlバージョン5.8.8における変更点 (perl588delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl588delta.pod'},
        {title:'Perlバージョン5.8.7における変更点 (perl587delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl587delta.pod'},
        {title:'Perlバージョン5.8.6における変更点 (perl586delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl586delta.pod'},
        {title:'Perlバージョン5.8.5における変更点 (perl585delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl585delta.pod'},
        {title:'Perlバージョン5.8.4における変更点 (perl584delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl584delta.pod'},
        {title:'Perlバージョン5.8.3における変更点 (perl583delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl583delta.pod'},
        {title:'Perlバージョン5.8.2における変更点 (perl582delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl582delta.pod'},
        {title:'Perlバージョン5.8.1における変更点 (perl581delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl581delta.pod'},
        {title:'Perlバージョン5.8.0における変更点 (perl58delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl58delta.pod'},
        {title:'Perlバージョン5.7.3における変更点 (perl573delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl573delta.pod'},
        {title:'Perlバージョン5.7.2における変更点 (perl572delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl572delta.pod'},
        {title:'Perlバージョン5.7.1における変更点 (perl571delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl571delta.pod'},
        {title:'Perlバージョン5.7.0における変更点 (perl570delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl570delta.pod'},
        {title:'Perlバージョン5.6.1における変更点 (perl561delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl561delta.pod'},
        {title:'Perlバージョン5.6における変更点 (perl56delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl56delta.pod'},
        {title:'Perlバージョン5.005における変更点 (perl5005delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl5005delta.pod'},
        {title:'Perlバージョン5.004における変更点 (perl5004delta)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/pod/perl5004delta.pod'},
        {title:'Perlアーティスティックライセンス (perlartistic)', url_ja:'http://d.hatena.ne.jp/keyword/%A5%E9%A5%A4%A5%BB%A5%F3%A5%B9', url_en:'http://search.cpan.org/dist/perl/pod/perlartistic.pod'},
        {title:'GNU ジェネラルパブリックライセンス (perlgpl)', url_ja:'http://d.hatena.ne.jp/keyword/%A5%D1%A5%D6%A5%EA%A5%C3%A5%AF', url_en:'http://search.cpan.org/dist/perl/pod/perlgpl.pod'},
        {title:'簡易中国語のためのPerl (perlcn)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.cn'},
        {title:'日本語のためのPerl (perljp)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.jp'},
        {title:'韓国語のためのPerl (perlko)', url_ja:'http://d.hatena.ne.jp/keyword/%B4%DA%B9%F1%B8%EC', url_en:'http://search.cpan.org/dist/perl/README.ko'},
        {title:'伝統的な中国語のためのPerl (perltw)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.tw'},
        {title:'AIXのためのPerlの注意点 (perlaix)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.aix'},
        {title:'AmigaOSのためのPerlの注意点 (perlamiga)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.amiga'},
        {title:'Apollo DomainOSのためのPerlの注意点 (perlapollo)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.apollo'},
        {title:'BeOSのためのPerlの注意点 (perlbeos)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.beos'},
        {title:'POSIX-BC BS2000のためのPerlの注意点 (perlbs2000)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.bs2000'},
        {title:'WinCEのためのPerlの注意点 (perlce)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.ce'},
        {title:'CygwinのためのPerlの注意点 (perlcygwin)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.cygwin'},
        {title:'DG/UXのためのPerlの注意点 (perldgux)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.dgux'},
        {title:'DOSのためのPerlの注意点 (perldos)', url_ja:'http://d.hatena.ne.jp/keyword/DOS', url_en:'http://search.cpan.org/dist/perl/README.dos'},
        {title:'EPOCのためのPerlの注意点 (perlepoc)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.epoc'},
        {title:'FreeBSDのためのPerlの注意点 (perlfreebsd)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.freebsd'},
        {title:'HaikuのためのPerlの注意点 (perlhaiku)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.haiku'},
        {title:'HP-UXのためのPerlの注意点 (perlhpux)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.hpux'},
        {title:'HurdのためのPerlの注意点 (perlhurd)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.hurd'},
        {title:'IrixのためのPerlの注意点 (perlirix)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.irix'},
        {title:'LinuxのためのPerlの注意点 (perllinux)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.linux'},
        {title:'Mac OS (Classic)のためのPerlの注意点 (perlmacos)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.macos'},
        {title:'Mac OS XのためのPerlの注意点 (perlmacosx)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.macosx'},
        {title:'MPE/iXのためのPerlの注意点 (perlmpeix)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.mpeix'},
        {title:'NetWareのためのPerlの注意点 (perlnetware)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.netware'},
        {title:'OpenBSDのためのPerlの注意点 (perlopenbsd)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.openbsd'},
        {title:'OS/2のためのPerlの注意点 (perlos2)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.os2'},
        {title:'OS/390のためのPerlの注意点 (perlos390)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.os390'},
        {title:'OS/400のためのPerlの注意点 (perlos400)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.os400'},
        {title:'Plan 9のためのPerlの注意点 (perlplan9)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.plan9'},
        {title:'QNXのためのPerlの注意点 (perlqnx)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.qnx'},
        {title:'RISC OSのためのPerlの注意点 (perlriscos)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.riscos'},
        {title:'SolarisのためのPerlの注意点 (perlsolaris)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.solaris'},
        {title:'SymbianのためのPerlの注意点 (perlsymbian)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.symbian'},
        {title:'Tru64のためのPerlの注意点 (perltru64)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.tru64'},
        {title:'UTSのためのPerlの注意点 (perluts)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.uts'},
        {title:'VM/ESAのためのPerlの注意点 (perlvmesa)', url_ja:'http://d.hatena.ne.jp/keyword/ESA', url_en:'http://search.cpan.org/dist/perl/README.vmesa'},
        {title:'VMSのためのPerlの注意点 (perlvms)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.vms'},
        {title:'Stratus VOSのためのPerlの注意点 (perlvos)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.vos'},
        {title:'WindowsのためのPerlの注意点 (perlwin32)', url_ja:'', url_en:'http://search.cpan.org/dist/perl/README.win32'},
    ];
}
